### ISSUE TITLE
Add integration tests for slack function

### ISSUE THREAD

**Issue by rmd6502** [rmd6502/progbot#10]
Perhaps using https://github.com/bblimke/webmock?

**Comment by rthbound** [comment]
This [stackoverflow answer](https://stackoverflow.com/a/32681901/1152759) highlights some problems we may face in adding integration tests to assert our app communicates results back to slack.

> Because your main thread doesn't halt execution, most of the time your assertion is run before the mail has been sent.

I think webmock is a good approach, but we'd still face the problems i'm mentioning here. Workarounds might include using `Thread.new` only in non-test environments or using Sidekiq with the following test configurations:

```
require 'sidekiq/testing'
Sidekiq::Testing.inline!
```

**Comment by cluesque** [comment]
Looks like that `Thread.new` stuff is attempting to do the communication with Slack in a way that it doesn't slow down the web request.  That's a fine goal, but I'm wondering about the tradeoffs.  

In a larger application I'd suggest something like delayed_job or sidekiq to do this work.  (And those have good testing stories.)  I'm guessing this application isn't big enough to justify the extra complexity (or a heroku dyno ... how's it hosted?)

Going back to the original premise ... is this web request so important that it *needs* to be performed in the background?  Keep in mind that you're losing a lot of visibility for managing the performance, capturing exceptions, etc.   If not, removing the threads simplifies both your hosting and testing stories.

If the web request is that important (or the slack callback that likely to be slow), then I'd suggest wrapping all the thread management in a library somewhere, and making that library simply be single threaded in the test environment.  (Or, like sidekiq, have configuration where the tests can make them inlined.)

**Comment by rmd6502** [comment]
A job queue would certainly be a cleaner way to do this - basically a slash command request will show an error timeout after 3 seconds if a 200 reply isn't received.  There's a response_url which is valid for 30 minutes, not sure if it only becomes valid after the POST response, but I haven't seen any issues with timing.
I think keeping it a background task or job is the right way to go, since eventually I hope we'll have enough opted-in users that we can't reply in 3 seconds.
I'll defer to those wiser than me in these matters though, what the final disposition should be.
