### ISSUE TITLE
add "are you registered to vote?" section of the sign-up, for which "no" button opens window to vote.gov

### ISSUE THREAD

**Issue by sdklos** [rmd6502/progbot#56]

**Comment by marcaaron** [comment]
Is this intended to be an input field on the sign up form itself ?
e.g. a checkbox that will trigger a new window once the user submits the sign up form ?

**Comment by sdklos** [comment]
There was some discussion about this - it can be whatever you think makes sense. I was thinking maybe a label/button combo that says"do you need to register to vote? Click here" that triggers a new window to open at vote.gov . If you have a different idea this one isn't set in stone
