### ISSUE TITLE
Add validation/flags to Project Import

### ISSUE THREAD

**Issue by sdklos** [rmd6502/progbot#64]
When Projects are imported from airtable, if they are missing certain fields, they should be flagged as needing admin attention

We will add a column "flagged", and if any of these qualities exist, the project will be checked "flagged" when it is imported from airtable. I believe the "flagged" column should actually be an array of strings so if a project is flagged for a variety of reasons we will easily be able to see why

*The Project is invalid (is missing a lead_id, name, legal structure, or tech stack entry)
*The Project is missing a progcode coordinator, or a repo link
*One of the team member slack ids didn't match anyone in the database

**Comment by stephenscapelliti** [comment]
Is it possible to issue an alert to a corresponding Slack channel?

**Comment by sdklos** [comment]
because this column will only be needed during the project import phase (and in this case it will all the flags will probably happen within the span of 10 minutes), i think having a place in the progbot admin panel to view flagged projects might be more helpful

**Comment by sdklos** [comment]
this has been done
