### ISSUE TITLE
Implement view functionality for ActiveAdmin pages

### ISSUE THREAD

**Issue by rmd6502** [rmd6502/progbot#70]
Bring it current with the current administration pages and schema

**Comment by rmd6502** [comment]
Skills and Projects currently fail

**Comment by rmd6502** [comment]
May have some dependencies on issue #71

**Comment by sdklos** [comment]
the recent changes i made have fixed at least the most obvious activeadmin - however there are likely remaining bugs, in addition there are many ways activeadmin could be functionally improved (working on the filters and search, the forms, etc. i can try to make a list if anyone is interested in doing this but would just like more guidance
