### ISSUE TITLE
Set Up Email Address to use with Mailer

### ISSUE THREAD

**Issue by sdklos** [rmd6502/progbot#75]
We want ProgBot to send emails to users when they first sign up, when they try to sign up with an email that already exists in our database, etc.

We need an email address for this purpose. We want an email address completely for progbot because its credentials will have to be stored. maybe progbot@progcode.org or something

**Comment by stephenscapelliti** [comment]
We can do this, but I'm wondering how to set it up for e-mails to go out automatically.  Perhaps we can discuss this in the channel, @sdklos?

**Comment by sdklos** [comment]
update: going to pursue using zapier/actionnetwork integration for sending emails from progbot

**Comment by sdklos** [comment]
update: now going to pursue setting up google mail smtp

**Comment by sdklos** [comment]
update: we have implemented the sendgrid heroku add-on
